### PR TITLE
Changed the driver description in the documentation

### PR DESCRIPTION
**Pull request by SachinJanani**

### CODE REVIEW

**Comment by dhavalstr** [comment]
Can one of the admins verify this patch?

**Comment by dhavalstr** [comment]
Can one of the admins verify this patch?

**Comment by dhavalstr** [comment]
Can one of the admins verify this patch?

**Comment by dhavalstr** [comment]
Can one of the admins verify this patch?

**Comment by dhavalstr** [comment]
Run prechekin

**Comment by dhavalstr** [comment]
Run prechekin

**Comment by dhavalstr** [comment]
Run prechekin

**Comment by sumwale** [comment]
obsolete

**Pull request closed without merging**
